pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - base=master
      - head=dev
    actions:
      merge:
        method: merge